FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD MyRetail.jar /opt/MyRetail/
EXPOSE 8080
WORKDIR /opt/MyRetail/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "MyRetail.jar"]
